### ISSUE TITLE
Add list section

### ISSUE THREAD

**Issue by lrmtheboss** [bs-community/awesome-minecraft#18]
Add a list section for good and useful lists such as https://github.com/NordicGamerFE/usefulmods

**Comment by g-plane** [comment]
What's "useful lists"?

**Comment by lrmtheboss** [comment]
lists with helpful information such as lists of client/server software, performance mods, and more, check the list I linked above for a good example

**Comment by g-plane** [comment]
We aren't going to create tables, but you can add something one by one by categories.

**Comment by lrmtheboss** [comment]
what about at the bottom adding an "Other useful resources" section where anything that does not fall under one of the categories can be put

**Comment by g-plane** [comment]
This sounds confusing. We can't just simply define something useful or not.

**Comment by lrmtheboss** [comment]
"other resources" would work as well

**Comment by g-plane** [comment]
While I don't mind adding a section like "other resources", I prefer adding something to specific category. Adding such section may make other contributors lazy to categorize their content.

**Comment by g-plane** [comment]
Inactive. Closing now.
