### ISSUE TITLE
Update Minecraft Wiki link

### ISSUE THREAD

**Issue by enderprism** [bs-community/awesome-minecraft#31]
i can't make a PR rn, but the Minecraft Wiki's website link should be updated to https://minecraft.wiki/

**Comment by g-plane** [comment]
Updated.

**Comment by Julmik647** [comment]
Chinese Minecraft wiki is still fandom in wiki, but it has new link:
https://zh.minecraft.wiki/
https://lzh.minecraft.wiki/
