### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [bs-community/awesome-minecraft#34]
Hi, there are a few broken links:

- [x] http://www.mcbbs.net/ (file: README.md, error: ECONNRESET)
- [x] http://betacraft.pl/server-archive/minecraft/ (file: README.md, error: ECONNRESET)
- [x] https://irisshaders.net/ (file: README.md, error: ECONNRESET)
- [x] https://faithful.team/ (file: README.md, status code: 521)
- [x] https://skin.lim-light.com/ (file: README.md, error: ENOTFOUND)
- [x] https://www.pocketmine.net/ (file: README.md, error: ECONNRESET)
- [x] https://powernukkit.org/ (file: README.md, error: ECONNRESET)
- [ ] https://minecraftcommand.science/ (file: README.md, error: ECONNRESET)

**Comment by g-plane** [comment]
[minecraftcommand.science](https://minecraftcommand.science/) works at this moment.
