### ISSUE TITLE
Request for Adding MCDOC

### ISSUE THREAD

**Issue by XtronXI** [bs-community/awesome-minecraft#35]
_I would've Pull Requested, but for some reason, i don't feel where to keep this_

**What is MCDOC?**

> MCDOC is the ultimate list for all Minecraft related Tools and Unlockers. Its contains tools for Bedrock, Education, China, Legends, Dungeons, Earth and their cross platform versions but doesnt contain Java (since there are already enough tools in awesome-minecraft and others). It also wraps up the Story of Cracking MCBE, Secret Marketplace Items and Guides.

**Website:** [https://mcdoc.openm.tech](https://mcdoc.openm.tech/)

> ***Published by [OpenM Team](https://github.com/OpenM-Project)***

**Comment by g-plane** [comment]
You can create a new sub-section under "Website" section, then add it there.

**Comment by Julmik647** [comment]
They changed link to https://mcdoc.site/
