### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by karx** [bs-community/awesome-minecraft#5]
In follow up to https://github.com/sindresorhus/awesome/issues/1755

This awesome list is *seriously* outdated. 
>> The awesome repo for Minecraft under gaming is seriously outdated

We do not even have sections mentioning the existence of resource packs and data packs.
A serious revamp is required.

It would be nice to understand the availability and thoughts of the original maintainers on this.

**Comment by g-plane** [comment]
We're feeling sorry about that. This repository is still under maintained, but our members of this organization can't have full-time on it, and we're maintainging some important softwares in this organization, such as https://github.com/bs-community/blessing-skin-server and https://github.com/bs-community/skinview3d .

Also, we don't have enough sources to collect and fill this awesome list, so any PRs are welcomed.

**Comment by karx** [comment]
awesome to hear from you. Expect a few major PR incoming, I am loving this librarian-ish work these days. :D

And also don't have my PC with me while am in isolation, can only do so much with this laptop.

**Comment by g-plane** [comment]
No problem. Just follow the guidelines and we're glad to see any PRs.

**Comment by lclcpg2018** [comment]
Sorry I may have been blunt in my initial comment, but I'm sure everyone would love to see a thriving awesome minecraft page...

I am nearly ready on my edit which contains an initial list of around 100 mods most common to the community - I'm just a huge noob at GitHub, and am not really sure how to operate all the pull/push/branching/merging and that sort of stuff..

I will finalize my commit based on a clone of this repo, and if possible please help with the GitHub bit!

Thanks, let's make this repo great again...

**Comment by lclcpg2018** [comment]
I might add these 100 mods are all Forge ones - if these renovations thrive even more I'll work on some more different things..

**Comment by g-plane** [comment]
Sounds great!

**Comment by g-plane** [comment]
For what is worth, we not only accept mods, but also server plugins or server jar, and even anything related to Minecraft (tutorials, etc).

**Comment by lclcpg2018** [comment]
Of course, but just as a starter. Also I realised I typed 100 mods - that was a mistake, it looked about 100 lines in my editor, in actual fact only about 30-40 mods, but I hope to come back!

**Comment by lclcpg2018** [comment]
How do you request to push your local branch of edits to the origin? I am having trouble trying to commit my edits... Sorry for being such a noob at GitHub..

**Comment by lclcpg2018** [comment]
I have opened a pull request, if that is what you are meant to do.
